----
version: '2.3'
# ---------------------------------------------------------------------------
# Copyright 2024 mwn-san
# Author: Mohammad Wildan Nuryulda
# Email: nuryulda@gmail.com
# GitHub: https://github.com/mwn-san
# ---------------------------------------------------------------------------

services:
  oracle-12c-enterprise:
    image: wvbirder/database-enterprise:12.2.0.1-slim
    container_name: oracle-12c-enterprise
    restart: unless-stopped
    network_mode: "host"
    environment:
      ORACLE_SID: "ORCLCDB"
      ORACLE_PDB: "ORCLPDB1"
      ORACLE_PWD: "password"
      ORACLE_CHARACTERSET: "AL32UTF8"
      ENABLE_ARCHIVELOG: "true"
      ENABLE_FORCE_LOGGING: "true"
      TRUE_CACHE: "true"
      PRIMARY_DB_CONN_STR: "<host>:1521/FREE"
      TZ: "Asia/Jakarta"
    volumes:
      - /home/oracle/data:/u01/app/oracle
      - /home/oracle/archive_log:/opt/oracle/archive_log
    ulimits:
      nofile:
        soft: 1024
        hard: 65536
      nproc:
        soft: 2047
        hard: 16384
      stack:
        soft: 10485760
        hard: 33554432
      memlock:
        soft: 3221225472
        hard: 3221225472
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6g

